{"1.1":{"info":{"author":"omid","author_email":"","bugtrack_url":null,"classifiers":[],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"database-error-ex-forex-next3","package_url":"https://pypi.org/project/database-error-ex-forex-next3/","platform":null,"project_url":"https://pypi.org/project/database-error-ex-forex-next3/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/database-error-ex-forex-next3/1.1/","requires_dist":null,"requires_python":"","summary":"database_error_ex_forex_next3","version":"1.1","yanked":false,"yanked_reason":null},"last_serial":20667087,"urls":[{"comment_text":"","digests":{"blake2b_256":"f33f73d8bc5656af96278b3d257f1eda96e94f6d1f65b3db61a8ea48801e4342","md5":"23b3fac9fd3060531f1bc3cb514235cb","sha256":"0f2f07aea7c8c828562b44ef8833c1073de3860ccff8075e4ad54f837cf41033"},"downloads":-1,"filename":"database_error_ex_forex_next3-1.1.tar.gz","has_sig":false,"md5_digest":"23b3fac9fd3060531f1bc3cb514235cb","packagetype":"sdist","python_version":"source","requires_python":null,"size":1485,"upload_time":"2023-11-16T18:59:21","upload_time_iso_8601":"2023-11-16T18:59:21.393174Z","url":"https://files.pythonhosted.org/packages/f3/3f/73d8bc5656af96278b3d257f1eda96e94f6d1f65b3db61a8ea48801e4342/database_error_ex_forex_next3-1.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.2":{"info":{"author":"omid","author_email":"","bugtrack_url":null,"classifiers":[],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"database-error-ex-forex-next3","package_url":"https://pypi.org/project/database-error-ex-forex-next3/","platform":null,"project_url":"https://pypi.org/project/database-error-ex-forex-next3/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/database-error-ex-forex-next3/1.2/","requires_dist":null,"requires_python":"","summary":"database_error_ex_forex_next3","version":"1.2","yanked":false,"yanked_reason":null},"last_serial":20667087,"urls":[{"comment_text":"","digests":{"blake2b_256":"fbf548ec04ea5e0acabfdefec766570aecf92617e7ae54b4b32a91b0150a3eb2","md5":"8535621a334168e4c8e039f497b32e0b","sha256":"1a949a3a7ebbea03d15bdd0d8981fcc0db98d56fde553689384857ceece44147"},"downloads":-1,"filename":"database_error_ex_forex_next3-1.2.tar.gz","has_sig":false,"md5_digest":"8535621a334168e4c8e039f497b32e0b","packagetype":"sdist","python_version":"source","requires_python":null,"size":1474,"upload_time":"2023-11-16T19:01:13","upload_time_iso_8601":"2023-11-16T19:01:13.840777Z","url":"https://files.pythonhosted.org/packages/fb/f5/48ec04ea5e0acabfdefec766570aecf92617e7ae54b4b32a91b0150a3eb2/database_error_ex_forex_next3-1.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}