{"0.1.10":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.10/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.10","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"702de7191175186542371f40a7a8c5b67fea82e43707a07e919412170ca6c575","md5":"4d00b39d2119d7accab09432ec3b9fda","sha256":"35bc114043db3bf1d5a882bd6fcacd954df28663a7535c619bea0c0c6c5ea40d"},"downloads":-1,"filename":"gpt_traceback-0.1.10-py3-none-any.whl","has_sig":false,"md5_digest":"4d00b39d2119d7accab09432ec3b9fda","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9037,"upload_time":"2023-01-26T01:18:26","upload_time_iso_8601":"2023-01-26T01:18:26.691273Z","url":"https://files.pythonhosted.org/packages/70/2d/e7191175186542371f40a7a8c5b67fea82e43707a07e919412170ca6c575/gpt_traceback-0.1.10-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"08ca9fb6ecf5570943d0345cd04e7dd926326ae7c7115bbd50a8dff7f590577d","md5":"c078f9ea451151fc395e01c79e58298a","sha256":"d525f63d1c1e812accc0fb9f7daf3de98fe94bd7ac9a54871d0c66b7bd9099d5"},"downloads":-1,"filename":"gpt_traceback-0.1.10.tar.gz","has_sig":false,"md5_digest":"c078f9ea451151fc395e01c79e58298a","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13657,"upload_time":"2023-01-26T01:18:28","upload_time_iso_8601":"2023-01-26T01:18:28.078798Z","url":"https://files.pythonhosted.org/packages/08/ca/9fb6ecf5570943d0345cd04e7dd926326ae7c7115bbd50a8dff7f590577d/gpt_traceback-0.1.10.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.11":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.11/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.11","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"59aaef825ae705ecca64fc9871bb651ee29773c751c23e596e92653aa2c51e0f","md5":"657186340d9a438680bdac5f9ef7e4e1","sha256":"410e153501eda0ec508b783113f3dab59b32e6f7fbcc564783114e1b1081d2e6"},"downloads":-1,"filename":"gpt_traceback-0.1.11-py3-none-any.whl","has_sig":false,"md5_digest":"657186340d9a438680bdac5f9ef7e4e1","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9175,"upload_time":"2023-01-26T01:25:20","upload_time_iso_8601":"2023-01-26T01:25:20.705175Z","url":"https://files.pythonhosted.org/packages/59/aa/ef825ae705ecca64fc9871bb651ee29773c751c23e596e92653aa2c51e0f/gpt_traceback-0.1.11-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"bccc62be2ae67c4eb71cad2e064751bea0f36815d5e98d24a2d4894e7b3c6ee8","md5":"aa674ae99768c0f9d29412d6c6e0bee1","sha256":"60cbcfbfe67de30a5d44350511adac492b8fc74e3e1118aabef6ea8bcdeed018"},"downloads":-1,"filename":"gpt_traceback-0.1.11.tar.gz","has_sig":false,"md5_digest":"aa674ae99768c0f9d29412d6c6e0bee1","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13780,"upload_time":"2023-01-26T01:25:21","upload_time_iso_8601":"2023-01-26T01:25:21.978065Z","url":"https://files.pythonhosted.org/packages/bc/cc/62be2ae67c4eb71cad2e064751bea0f36815d5e98d24a2d4894e7b3c6ee8/gpt_traceback-0.1.11.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.12":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.12/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.12","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"9785d1d06700b73433e97a091238ce93027b97300ea48bae1a30221a68221786","md5":"c5ccdd18b3158ae7b1fff42472c925c2","sha256":"12223d8519fa2ed02936162e2c44b09844b19d23578e5a493d0768d4cf8c99d5"},"downloads":-1,"filename":"gpt_traceback-0.1.12-py3-none-any.whl","has_sig":false,"md5_digest":"c5ccdd18b3158ae7b1fff42472c925c2","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9169,"upload_time":"2023-01-26T01:30:10","upload_time_iso_8601":"2023-01-26T01:30:10.433627Z","url":"https://files.pythonhosted.org/packages/97/85/d1d06700b73433e97a091238ce93027b97300ea48bae1a30221a68221786/gpt_traceback-0.1.12-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"5cdeea3c6ed3712c983cec80f3cbb93f576fee848b4ccafaf6afc301bb7595cf","md5":"2c41e8f50880de8b98b29465a9b1e275","sha256":"a1ae436f3f76e529aed90271f5d59a3001403c04ed0789d1ab646e6524c827aa"},"downloads":-1,"filename":"gpt_traceback-0.1.12.tar.gz","has_sig":false,"md5_digest":"2c41e8f50880de8b98b29465a9b1e275","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13794,"upload_time":"2023-01-26T01:30:12","upload_time_iso_8601":"2023-01-26T01:30:12.019228Z","url":"https://files.pythonhosted.org/packages/5c/de/ea3c6ed3712c983cec80f3cbb93f576fee848b4ccafaf6afc301bb7595cf/gpt_traceback-0.1.12.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.14":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.14/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.14","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"984314aafb8896a859bd61a8935d3b20732f6915d2ab23530432904e637b0816","md5":"08edae1005c800d65e4b2119861ca3e7","sha256":"d8ba52751333e574ddc549e9cae9609bfa0dc04d00c1f8808294dafb5d79fb46"},"downloads":-1,"filename":"gpt_traceback-0.1.14-py3-none-any.whl","has_sig":false,"md5_digest":"08edae1005c800d65e4b2119861ca3e7","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9383,"upload_time":"2023-01-26T01:37:05","upload_time_iso_8601":"2023-01-26T01:37:05.857680Z","url":"https://files.pythonhosted.org/packages/98/43/14aafb8896a859bd61a8935d3b20732f6915d2ab23530432904e637b0816/gpt_traceback-0.1.14-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"275be07f8962d0549c82305a9e898d82e673d39b29ec020246024bae1cc3dfa8","md5":"045bb931f636b8063587ecd44a04c83a","sha256":"5997eeec8daa66f96b29607b295f83344d28f30c02bb4734cc3c6c4f359eeee4"},"downloads":-1,"filename":"gpt_traceback-0.1.14.tar.gz","has_sig":false,"md5_digest":"045bb931f636b8063587ecd44a04c83a","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13833,"upload_time":"2023-01-26T01:37:07","upload_time_iso_8601":"2023-01-26T01:37:07.266173Z","url":"https://files.pythonhosted.org/packages/27/5b/e07f8962d0549c82305a9e898d82e673d39b29ec020246024bae1cc3dfa8/gpt_traceback-0.1.14.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.15":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.15/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.15","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"a3163f6f0e4e2baf92e6d4f92eae1df7b6d59f00c34e85195f083584a90d6f90","md5":"c76345c3d741dbbe8820a69c65c752e7","sha256":"06e8ca4c6aca796465616bc3bca44c56b1f8aa9d1e2d27ea728a3f80f16e5ca4"},"downloads":-1,"filename":"gpt_traceback-0.1.15-py3-none-any.whl","has_sig":false,"md5_digest":"c76345c3d741dbbe8820a69c65c752e7","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9420,"upload_time":"2023-01-26T01:46:47","upload_time_iso_8601":"2023-01-26T01:46:47.250085Z","url":"https://files.pythonhosted.org/packages/a3/16/3f6f0e4e2baf92e6d4f92eae1df7b6d59f00c34e85195f083584a90d6f90/gpt_traceback-0.1.15-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"0927ab9cb715b5889bdbb13032cfdc45cffb7e0546e0e05ba70d00e28eaf702a","md5":"93c7e75e8eb6ad89f5cf068827e601f0","sha256":"3c5bbfa61629e652663621cfcc5e632653e60227d72007d891f2484c86b054a6"},"downloads":-1,"filename":"gpt_traceback-0.1.15.tar.gz","has_sig":false,"md5_digest":"93c7e75e8eb6ad89f5cf068827e601f0","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13861,"upload_time":"2023-01-26T01:46:48","upload_time_iso_8601":"2023-01-26T01:46:48.289961Z","url":"https://files.pythonhosted.org/packages/09/27/ab9cb715b5889bdbb13032cfdc45cffb7e0546e0e05ba70d00e28eaf702a/gpt_traceback-0.1.15.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.16":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.16/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.16","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"43d9f8770a1d948c54f9c7033557ca8bbd5c48a04e3fe2c02284a8c554db34ec","md5":"dc200f3b8cdf30ff33fd23df790d5f4c","sha256":"6c44416f2af2545bd7b416c5edc1a01e75da790e6a589269a8fd77ae3c38bc67"},"downloads":-1,"filename":"gpt_traceback-0.1.16-py3-none-any.whl","has_sig":false,"md5_digest":"dc200f3b8cdf30ff33fd23df790d5f4c","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9507,"upload_time":"2023-01-26T01:55:16","upload_time_iso_8601":"2023-01-26T01:55:16.337019Z","url":"https://files.pythonhosted.org/packages/43/d9/f8770a1d948c54f9c7033557ca8bbd5c48a04e3fe2c02284a8c554db34ec/gpt_traceback-0.1.16-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"a0b81d5ec83f1fb071d1de1e8bac7df456f369cc4aefac01b60510f04b260055","md5":"ed4fd5d832d261805df07438aeeb9c8c","sha256":"7da11b34903f49a4d90dc9afe84407297ad57ee3a4252e0d988a7c6a977cc179"},"downloads":-1,"filename":"gpt_traceback-0.1.16.tar.gz","has_sig":false,"md5_digest":"ed4fd5d832d261805df07438aeeb9c8c","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13909,"upload_time":"2023-01-26T01:55:18","upload_time_iso_8601":"2023-01-26T01:55:18.077457Z","url":"https://files.pythonhosted.org/packages/a0/b8/1d5ec83f1fb071d1de1e8bac7df456f369cc4aefac01b60510f04b260055/gpt_traceback-0.1.16.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.17":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.17/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.17","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"cfeb399f0e9aa3bacc303266debf352e8ef91319679f35bf35e51ed0d125e3ff","md5":"c4cbcafe520b5c7fa6e029a5b1c3eb24","sha256":"d31f29ca9050cb456fd7530a24f9013285bc48de98e4f646acd138883c00bd74"},"downloads":-1,"filename":"gpt_traceback-0.1.17-py3-none-any.whl","has_sig":false,"md5_digest":"c4cbcafe520b5c7fa6e029a5b1c3eb24","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9518,"upload_time":"2023-01-26T01:57:41","upload_time_iso_8601":"2023-01-26T01:57:41.871315Z","url":"https://files.pythonhosted.org/packages/cf/eb/399f0e9aa3bacc303266debf352e8ef91319679f35bf35e51ed0d125e3ff/gpt_traceback-0.1.17-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"8c5167bd93b4dec45d6f889d394d7df296b601c75fab1fc203d274ea33a41482","md5":"050887e008cdb3794be285c4fb523f27","sha256":"6c1e7189f6a93c9595eb58670d33299600a160f210e46c6b1511bcf218b70f78"},"downloads":-1,"filename":"gpt_traceback-0.1.17.tar.gz","has_sig":false,"md5_digest":"050887e008cdb3794be285c4fb523f27","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13931,"upload_time":"2023-01-26T01:57:43","upload_time_iso_8601":"2023-01-26T01:57:43.452271Z","url":"https://files.pythonhosted.org/packages/8c/51/67bd93b4dec45d6f889d394d7df296b601c75fab1fc203d274ea33a41482/gpt_traceback-0.1.17.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.18":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.18/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.18","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"c284aefffd9c91c414ce6293cd0bad30e141e74a81e0199ebe0df0b1259289eb","md5":"35ce1e08ba54f25d159120eb9f8d6ae9","sha256":"f86088a2568ee2d38d286aa942a94fcecbeb77842ba5b307c97084696dd4bc4a"},"downloads":-1,"filename":"gpt_traceback-0.1.18-py3-none-any.whl","has_sig":false,"md5_digest":"35ce1e08ba54f25d159120eb9f8d6ae9","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9521,"upload_time":"2023-01-26T01:59:37","upload_time_iso_8601":"2023-01-26T01:59:37.988525Z","url":"https://files.pythonhosted.org/packages/c2/84/aefffd9c91c414ce6293cd0bad30e141e74a81e0199ebe0df0b1259289eb/gpt_traceback-0.1.18-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"f133bee1016cc945d9c6249928a72594939f15b9ede89f2d44588fad0891d024","md5":"92b4e844d9e5608bd01d7b32dbe842aa","sha256":"7c0034f055fb0ae5b0bbf6a2efc14d542457a89c5e2085cf3158689c6c6e32a4"},"downloads":-1,"filename":"gpt_traceback-0.1.18.tar.gz","has_sig":false,"md5_digest":"92b4e844d9e5608bd01d7b32dbe842aa","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13920,"upload_time":"2023-01-26T01:59:39","upload_time_iso_8601":"2023-01-26T01:59:39.551537Z","url":"https://files.pythonhosted.org/packages/f1/33/bee1016cc945d9c6249928a72594939f15b9ede89f2d44588fad0891d024/gpt_traceback-0.1.18.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.19":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.19/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.19","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"24913fbaa663959730910b9e8bed018331adefb41b526d99bad6f45502a0069d","md5":"3b6ea5598b25c8474275e1fa8543230b","sha256":"616bcb41953be44f70f77223c182b9aea3845780bba6a64a4c1dd754f58851a8"},"downloads":-1,"filename":"gpt_traceback-0.1.19-py3-none-any.whl","has_sig":false,"md5_digest":"3b6ea5598b25c8474275e1fa8543230b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9555,"upload_time":"2023-01-26T02:07:44","upload_time_iso_8601":"2023-01-26T02:07:44.969788Z","url":"https://files.pythonhosted.org/packages/24/91/3fbaa663959730910b9e8bed018331adefb41b526d99bad6f45502a0069d/gpt_traceback-0.1.19-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"5ab5fdf5f510fb52aeedb6274b1880c48a9dc960e5a8eeb20d714dec6b935116","md5":"ebf050286d3f954de9325de78d36f997","sha256":"312b675afb7e5ee0997ccb728ce1a4d097267ddcf813c5f79dad3677a600815e"},"downloads":-1,"filename":"gpt_traceback-0.1.19.tar.gz","has_sig":false,"md5_digest":"ebf050286d3f954de9325de78d36f997","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13951,"upload_time":"2023-01-26T02:07:46","upload_time_iso_8601":"2023-01-26T02:07:46.373126Z","url":"https://files.pythonhosted.org/packages/5a/b5/fdf5f510fb52aeedb6274b1880c48a9dc960e5a8eeb20d714dec6b935116/gpt_traceback-0.1.19.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.20":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.20/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.20","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"c781409894b535acf73dfd30e8ce9c8a03b0cba01aaaacc1f25983ffdd3a3d37","md5":"543fde15fcbc8652eb71308363ea91de","sha256":"48c40d3b2cc5de6a68b3cb06d781c855c9b56eb3fa9646a89fe0d395865cea19"},"downloads":-1,"filename":"gpt_traceback-0.1.20-py3-none-any.whl","has_sig":false,"md5_digest":"543fde15fcbc8652eb71308363ea91de","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9533,"upload_time":"2023-01-26T02:15:12","upload_time_iso_8601":"2023-01-26T02:15:12.790877Z","url":"https://files.pythonhosted.org/packages/c7/81/409894b535acf73dfd30e8ce9c8a03b0cba01aaaacc1f25983ffdd3a3d37/gpt_traceback-0.1.20-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"7c2ac9d5a14d1ab0649435e366e9522dc908a3393b31c8b67da9965335c9b949","md5":"14691fc24390e6d2ef6ad24b104b5c38","sha256":"03d17da525ad565c939f70f5709699b74cbe68472700ced6f221efc4f9462713"},"downloads":-1,"filename":"gpt_traceback-0.1.20.tar.gz","has_sig":false,"md5_digest":"14691fc24390e6d2ef6ad24b104b5c38","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13949,"upload_time":"2023-01-26T02:15:14","upload_time_iso_8601":"2023-01-26T02:15:14.351163Z","url":"https://files.pythonhosted.org/packages/7c/2a/c9d5a14d1ab0649435e366e9522dc908a3393b31c8b67da9965335c9b949/gpt_traceback-0.1.20.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.21":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.21/","requires_dist":["requests","rich","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.21","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"2ba11df2dea3a038a9c4a998df21187cbff5d2966b35c00415754b4bbdcc2098","md5":"e8225bc83791dc7ccfdff8ac472ce055","sha256":"9d01414fd08381b7db56ba0038464bf0c36ff0ac715ae14f99752aedb98beb11"},"downloads":-1,"filename":"gpt_traceback-0.1.21-py3-none-any.whl","has_sig":false,"md5_digest":"e8225bc83791dc7ccfdff8ac472ce055","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9540,"upload_time":"2023-01-26T02:25:25","upload_time_iso_8601":"2023-01-26T02:25:25.887638Z","url":"https://files.pythonhosted.org/packages/2b/a1/1df2dea3a038a9c4a998df21187cbff5d2966b35c00415754b4bbdcc2098/gpt_traceback-0.1.21-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"e671f397e4bab7caa010cd1ce93addd703b3d6c8f6076d205580beb3a9d32036","md5":"a4ccad27a8d5cec146bd56e65797efbe","sha256":"4a577bbd721d1aa9698b1a70468fefee4fa7dfa4a1606fe2be67661d86b1f818"},"downloads":-1,"filename":"gpt_traceback-0.1.21.tar.gz","has_sig":false,"md5_digest":"a4ccad27a8d5cec146bd56e65797efbe","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":13968,"upload_time":"2023-01-26T02:25:27","upload_time_iso_8601":"2023-01-26T02:25:27.447782Z","url":"https://files.pythonhosted.org/packages/e6/71/f397e4bab7caa010cd1ce93addd703b3d6c8f6076d205580beb3a9d32036/gpt_traceback-0.1.21.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.22":{"info":{"author":"Franz Krekeler","author_email":"filmfranz@findmeontwitter.com","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Intended Audience :: Developers","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3 :: Only","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9","Topic :: Software Development :: Build Tools"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/franz101/gpt-exception","keywords":"gpt,jupyter,colab,traceback,debugging","license":"","maintainer":"","maintainer_email":"","name":"gpt-traceback","package_url":"https://pypi.org/project/gpt-traceback/","platform":null,"project_url":"https://pypi.org/project/gpt-traceback/","project_urls":{"Bug Reports":"https://github.com/franz101/gpt-exception/issues","Documentation":"https://github.com/franz101/gpt-exception","Homepage":"https://github.com/franz101/gpt-exception","Source Code":"https://github.com/franz101/gpt-exception"},"provides_extra":null,"release_url":"https://pypi.org/project/gpt-traceback/0.1.22/","requires_dist":["requests","rich","pygments","check-manifest ; extra == 'dev'"],"requires_python":">=3.6","summary":"Debug your exceptions with GPT","version":"0.1.22","yanked":false,"yanked_reason":null},"last_serial":16571445,"urls":[{"comment_text":"","digests":{"blake2b_256":"c3c214abecfec2f0097ecb29ec044630962565f447d4387c99931bbdb2c5d97e","md5":"010d6ff177d79fb23c72299c2feee27c","sha256":"3da67dfd20edd101df3f62072c64eef2802b855bfdcf5cee0c5c04d6736e9e67"},"downloads":-1,"filename":"gpt_traceback-0.1.22-py3-none-any.whl","has_sig":false,"md5_digest":"010d6ff177d79fb23c72299c2feee27c","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":9574,"upload_time":"2023-01-26T02:34:56","upload_time_iso_8601":"2023-01-26T02:34:56.917829Z","url":"https://files.pythonhosted.org/packages/c3/c2/14abecfec2f0097ecb29ec044630962565f447d4387c99931bbdb2c5d97e/gpt_traceback-0.1.22-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"2db775159b1e8227518d9fe0f476b2d411834557a3c85a1a06b4a8c7f1a2808c","md5":"71b31021274a0c2a896d391a68ef5b15","sha256":"bc892f7ba067012d4db300a2a39a36798ca976ea4317d4d1ba583185649fc82e"},"downloads":-1,"filename":"gpt_traceback-0.1.22.tar.gz","has_sig":false,"md5_digest":"71b31021274a0c2a896d391a68ef5b15","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":14020,"upload_time":"2023-01-26T02:34:58","upload_time_iso_8601":"2023-01-26T02:34:58.590020Z","url":"https://files.pythonhosted.org/packages/2d/b7/75159b1e8227518d9fe0f476b2d411834557a3c85a1a06b4a8c7f1a2808c/gpt_traceback-0.1.22.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}