{"1.0":{"info":{"author":"Dieter Maurer","author_email":"dieter@handshake.de","bugtrack_url":null,"classifiers":["Development Status :: 5 - Production/Stable","Framework :: Zope2","Intended Audience :: Developers","License :: OSI Approved :: Zope Public License","Operating System :: OS Independent","Programming Language :: Python","Topic :: Utilities"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://pypi.python.org/pypi/dm.zodb.repair","keywords":"ZODB recovery","license":"ZPL","maintainer":null,"maintainer_email":null,"name":"dm.zodb.repair","package_url":"https://pypi.org/project/dm.zodb.repair/","platform":"UNKNOWN","project_url":"https://pypi.org/project/dm.zodb.repair/","project_urls":{"Download":"UNKNOWN","Homepage":"http://pypi.python.org/pypi/dm.zodb.repair"},"provides_extra":null,"release_url":"https://pypi.org/project/dm.zodb.repair/1.0/","requires_dist":null,"requires_python":null,"summary":"ZODB: recover lost objects from a backup","version":"1.0","yanked":false,"yanked_reason":null},"last_serial":791262,"urls":[{"comment_text":"","digests":{"blake2b_256":"e2739fcbb68352ecd1d6a820a3c87c3c9ba6fd4c10fee1e39e6c9c5f9c593a53","md5":"650fb9abd6a4b9ce6d0b668172582537","sha256":"c0e3cf6496f63768d1f271cc86c16c47ec04ce1b3726ccfbb168cdeb6f8bbfcc"},"downloads":-1,"filename":"dm.zodb.repair-1.0.tar.gz","has_sig":false,"md5_digest":"650fb9abd6a4b9ce6d0b668172582537","packagetype":"sdist","python_version":"source","requires_python":null,"size":2934,"upload_time":"2010-11-10T10:58:03","upload_time_iso_8601":"2010-11-10T10:58:03.127194Z","url":"https://files.pythonhosted.org/packages/e2/73/9fcbb68352ecd1d6a820a3c87c3c9ba6fd4c10fee1e39e6c9c5f9c593a53/dm.zodb.repair-1.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}