{"0.1.6":{"info":{"author":"GoPythonGo.com","author_email":"info@gopythongo.com, scottb@opennetworking.org","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"django-dbconn-retry-python27","package_url":"https://pypi.org/project/django-dbconn-retry-python27/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry-python27/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry-python27/0.1.6/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.6","yanked":false,"yanked_reason":null},"last_serial":4034306,"urls":[{"comment_text":"","digests":{"blake2b_256":"914b38570cd9cbdd4e2d2f73647f3f8ca8dbfa028c60656765599e7a3af2414e","md5":"187c100088894d57b98e60db0344435f","sha256":"e5356070e98dd1f547dc858a22dd7959cd63cebd22fe3e14b95e768e797bd44f"},"downloads":-1,"filename":"django-dbconn-retry-python27-0.1.6.tar.gz","has_sig":false,"md5_digest":"187c100088894d57b98e60db0344435f","packagetype":"sdist","python_version":"source","requires_python":null,"size":7734,"upload_time":"2018-07-05T19:58:39","upload_time_iso_8601":"2018-07-05T19:58:39.955019Z","url":"https://files.pythonhosted.org/packages/91/4b/38570cd9cbdd4e2d2f73647f3f8ca8dbfa028c60656765599e7a3af2414e/django-dbconn-retry-python27-0.1.6.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}