{"0.0.1":{"info":{"author":"Fernando Celmer","author_email":"email@fernandocelmer.com","bugtrack_url":null,"classifiers":["Intended Audience :: Developers","License :: OSI Approved :: MIT License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/UpyExplorer/upy-error","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"upy-error","package_url":"https://pypi.org/project/upy-error/","platform":"","project_url":"https://pypi.org/project/upy-error/","project_urls":{"Homepage":"https://github.com/UpyExplorer/upy-error"},"provides_extra":null,"release_url":"https://pypi.org/project/upy-error/0.0.1/","requires_dist":null,"requires_python":">=3.6","summary":"Python Trace Error","version":"0.0.1","yanked":false,"yanked_reason":null},"last_serial":18114936,"urls":[{"comment_text":"","digests":{"blake2b_256":"e20400d40500da9470131aeff569716c3be3d5a2f8c0b5a8c5eea6b7332d7fde","md5":"01bbe9d1fa1b82edbaf90abd87616423","sha256":"8ce1c4d6b83e16167bf6c803053054cc264b8994f21d6fca37d16ef9c3d48df5"},"downloads":-1,"filename":"upy_error-0.0.1-py2.py3-none-any.whl","has_sig":false,"md5_digest":"01bbe9d1fa1b82edbaf90abd87616423","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":">=3.6","size":2188,"upload_time":"2022-01-15T21:35:53","upload_time_iso_8601":"2022-01-15T21:35:53.958912Z","url":"https://files.pythonhosted.org/packages/e2/04/00d40500da9470131aeff569716c3be3d5a2f8c0b5a8c5eea6b7332d7fde/upy_error-0.0.1-py2.py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"523a9fca8d8fd262fe576956a3c8024f5b4ea102ce63eb31f75fea5fa7f78954","md5":"01d5f897988891239dbe6d48badb6ab7","sha256":"609dfc46bfd410adbdcdfd5966633bfb8b9bc2b012df549f94ba75f9fce78fde"},"downloads":-1,"filename":"upy-error-0.0.1.tar.gz","has_sig":false,"md5_digest":"01d5f897988891239dbe6d48badb6ab7","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":2072,"upload_time":"2022-01-15T21:35:55","upload_time_iso_8601":"2022-01-15T21:35:55.743895Z","url":"https://files.pythonhosted.org/packages/52/3a/9fca8d8fd262fe576956a3c8024f5b4ea102ce63eb31f75fea5fa7f78954/upy-error-0.0.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.2":{"info":{"author":"Fernando Celmer","author_email":"email@fernandocelmer.com","bugtrack_url":null,"classifiers":["Intended Audience :: Developers","License :: OSI Approved :: MIT License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/UpyExplorer/upy-error","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"upy-error","package_url":"https://pypi.org/project/upy-error/","platform":null,"project_url":"https://pypi.org/project/upy-error/","project_urls":{"Homepage":"https://github.com/UpyExplorer/upy-error"},"provides_extra":null,"release_url":"https://pypi.org/project/upy-error/0.0.2/","requires_dist":null,"requires_python":">=3.6","summary":"Python Trace Error","version":"0.0.2","yanked":false,"yanked_reason":null},"last_serial":18114936,"urls":[{"comment_text":"","digests":{"blake2b_256":"abc46abdc541f1478543f7aa05298ec0e75825b6e5272e87f7a75230f2913b1b","md5":"826adedaba1b854941e70d7f80892677","sha256":"42ce128f084f6f6a02f53a19fc86ff8b2fc9b61f379f7343b16e7235d65916c2"},"downloads":-1,"filename":"upy_error-0.0.2-py2.py3-none-any.whl","has_sig":false,"md5_digest":"826adedaba1b854941e70d7f80892677","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":">=3.6","size":3015,"upload_time":"2022-07-23T05:03:21","upload_time_iso_8601":"2022-07-23T05:03:21.091941Z","url":"https://files.pythonhosted.org/packages/ab/c4/6abdc541f1478543f7aa05298ec0e75825b6e5272e87f7a75230f2913b1b/upy_error-0.0.2-py2.py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"32af0c26dbe990fde40cfa6f32d1725d51a410eeebfa3c02236cfe83f55e2e2f","md5":"bb0bba1cd339a6ff10b036fa11286609","sha256":"1443e61ba8ec8c610ad761de20b3ea1604927fe876fdbb096afe043e72c7f383"},"downloads":-1,"filename":"upy-error-0.0.2.tar.gz","has_sig":false,"md5_digest":"bb0bba1cd339a6ff10b036fa11286609","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":2686,"upload_time":"2022-07-23T05:03:22","upload_time_iso_8601":"2022-07-23T05:03:22.858984Z","url":"https://files.pythonhosted.org/packages/32/af/0c26dbe990fde40cfa6f32d1725d51a410eeebfa3c02236cfe83f55e2e2f/upy-error-0.0.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.3":{"info":{"author":"Fernando Celmer","author_email":"email@fernandocelmer.com","bugtrack_url":null,"classifiers":["Intended Audience :: Developers","License :: OSI Approved :: MIT License","Natural Language :: English","Operating System :: OS Independent","Programming Language :: Python :: 3.10","Programming Language :: Python :: 3.11","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/UpyExplorer/upy-error","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"upy-error","package_url":"https://pypi.org/project/upy-error/","platform":null,"project_url":"https://pypi.org/project/upy-error/","project_urls":{"Homepage":"https://github.com/UpyExplorer/upy-error"},"provides_extra":null,"release_url":"https://pypi.org/project/upy-error/0.0.3/","requires_dist":null,"requires_python":">=3.6","summary":"Python Trace Error","version":"0.0.3","yanked":false,"yanked_reason":null},"last_serial":18114936,"urls":[{"comment_text":"","digests":{"blake2b_256":"41db396164e11c395dc19ef3490ff71ab1fd6fbca767ef35a59da9914ef5f307","md5":"6148f66dbab098c22031959e92008856","sha256":"545b0e84bffb220aab8caaa7eff6c2a400a7ed9b430d7b55b3d0b47c753f8307"},"downloads":-1,"filename":"upy_error-0.0.3-py2.py3-none-any.whl","has_sig":false,"md5_digest":"6148f66dbab098c22031959e92008856","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":">=3.6","size":3122,"upload_time":"2023-05-16T00:16:55","upload_time_iso_8601":"2023-05-16T00:16:55.837802Z","url":"https://files.pythonhosted.org/packages/41/db/396164e11c395dc19ef3490ff71ab1fd6fbca767ef35a59da9914ef5f307/upy_error-0.0.3-py2.py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"1934cd281a63a9213bc32994f953fe2b40109687c5cdcce767e43571ab06a35c","md5":"6b8b4dcc5449e1cd2a1fd837aafcef2d","sha256":"fffb5593ed88978487cf45209f189cb12a78bfab66c7f4ba123f101aeaba3f16"},"downloads":-1,"filename":"upy-error-0.0.3.tar.gz","has_sig":false,"md5_digest":"6b8b4dcc5449e1cd2a1fd837aafcef2d","packagetype":"sdist","python_version":"source","requires_python":">=3.6","size":2937,"upload_time":"2023-05-16T00:16:57","upload_time_iso_8601":"2023-05-16T00:16:57.359807Z","url":"https://files.pythonhosted.org/packages/19/34/cd281a63a9213bc32994f953fe2b40109687c5cdcce767e43571ab06a35c/upy-error-0.0.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}